---
- name: Install apps on Fedora
  hosts: localhost
  become: yes

  vars:
    vmware_installer_url: "https://www.vmware.com/go/getworkstation-linux"  # Official VMware download link

  tasks:
    - name: Ensure dnf-plugins-core is installed
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Ensure Flatpak is installed
      dnf:
        name: flatpak
        state: present

    - name: Add Flathub remote for Flatpak
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: /var/lib/flatpak/repo/flathub

    - name: Enable RPM Fusion free and nonfree repositories
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
      ignore_errors: yes

    - name: Install Flameshot
      dnf:
        name: flameshot
        state: present

    - name: Install Steam
      dnf:
        name: steam
        state: present

    - name: Install Discord via Flatpak
      flatpak:
        name: com.discordapp.Discord
        state: present
        remote: flathub

    - name: Install Minecraft via Flatpak
      flatpak:
        name: com.mojang.Minecraft
        state: present
        remote: flathub

    - name: Install Bitwarden via Flatpak
      flatpak:
        name: com.bitwarden.desktop
        state: present
        remote: flathub

    - name: Install Burp Suite Community via Flatpak (Flathub)
      flatpak:
        name: net.portswigger.BurpSuite-Community
        state: present
        remote: flathub

    - name: Install Node.js and npm
      dnf:
        name: nodejs
        state: present

    - name: Install Docker
      dnf:
        name:
          - docker
          - docker-compose
        state: present

    - name: Ensure Docker service is enabled and started
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Download VMware Workstation Pro installer
      get_url:
        url: "{{ vmware_installer_url }}"
        dest: /tmp/VMware-Workstation.bundle
        mode: '0755'

    - name: Run VMware Workstation Pro installer
      command: /tmp/VMware-Workstation.bundle --console --required
      args:
        creates: /usr/lib/vmware

    # --- Wireshark install & non-root capture setup ---
    - name: Install Wireshark (GUI and CLI) and libcap
      dnf:
        name:
          - wireshark-qt    # GUI
          - wireshark-cli   # tshark & dumpcap
          - libcap          # provides setcap
        state: present

    - name: Ensure wireshark group exists
      group:
        name: wireshark
        state: present
        system: yes

    - name: Add current user to wireshark group
      user:
        name: "{{ ansible_user }}"
        groups: wireshark
        append: yes

    - name: Locate dumpcap binary
      command: "command -v dumpcap"
      register: dumpcap_path
      changed_when: false
      failed_when: false

    - name: Fail early if dumpcap not found
      fail:
        msg: "dumpcap binary not found after installing wireshark. Manual investigation required."
      when: dumpcap_path.stdout == ""

    - name: Set capabilities on dumpcap so non-root users can capture packets
      command: "setcap cap_net_raw,cap_net_admin+eip {{ dumpcap_path.stdout }}"
      when: dumpcap_path.stdout != ""

    - name: Ensure dumpcap is owned by root and executable
      file:
        path: "{{ dumpcap_path.stdout }}"
        owner: root
        group: root
        mode: '0755'
      when: dumpcap_path.stdout != ""

    - name: Inform user about re-login needed for group membership
      debug:
        msg: "User '{{ ansible_user }}' was added to the 'wireshark' group. They must log out and back in (or run 'newgrp wireshark') for the group change to take effect."
