---
- name: Setup essential tools on Linux Mint 22 (based on Ubuntu 24.04)
  hosts: localhost
  become: yes

  tasks:
    # --- Package updates ---
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes

    # --- Core utilities ---
    - name: Ensure core tools are installed
      apt:
        name:
          - curl
          - wget
          - git
          - vim
          - flatpak
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present

    # --- Add Flathub remote ---
    - name: Add Flathub remote for Flatpak
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: /var/lib/flatpak/repo/flathub

    # --- App installs (APT) ---
    - name: Install Flameshot
      apt:
        name: flameshot
        state: present

    - name: Install Steam
      apt:
        name: steam-installer
        state: present

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Ensure Docker service is enabled and started
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_facts['env']['USER'] | default(ansible_user) }}"
        groups: docker
        append: yes

    # --- Flatpak apps ---
    - name: Install Discord via Flatpak
      flatpak:
        name: com.discordapp.Discord
        state: present
        remote: flathub

    - name: Install Minecraft via Flatpak
      flatpak:
        name: com.mojang.Minecraft
        state: present
        remote: flathub

    - name: Install Bitwarden via Flatpak
      flatpak:
        name: com.bitwarden.desktop
        state: present
        remote: flathub

    - name: Install Burp Suite Community via Flatpak
      flatpak:
        name: net.portswigger.BurpSuite-Community
        state: present
        remote: flathub

    # --- Wireshark setup (non-root capture) ---
    - name: Install Wireshark and dependencies
      apt:
        name:
          - wireshark
          - libcap2-bin
        state: present

    - name: Ensure wireshark group exists
      group:
        name: wireshark
        state: present

    - name: Add current user to wireshark group
      user:
        name: "{{ ansible_facts['env']['USER'] | default(ansible_user) }}"
        groups: wireshark
        append: yes

    - name: Locate dumpcap binary
      command: "command -v dumpcap"
      register: dumpcap_path
      changed_when: false
      failed_when: false

    - name: Set dumpcap capabilities for non-root packet capture
      command: "setcap cap_net_raw,cap_net_admin+eip {{ dumpcap_path.stdout }}"
      when: dumpcap_path.stdout != ""

    - name: Inform user about re-login needed for group membership
      debug:
        msg: "Re-login or run 'newgrp wireshark' to apply Wireshark group membership."

    # --- Keyboard Shortcuts (Cinnamon) ---
    # System Monitor (Ctrl+Shift+Esc)
    - name: Create custom shortcut for System Monitor (Cinnamon)
      command: >
        gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/
        name 'System Monitor'
      ignore_errors: yes

    - name: Set System Monitor command (Cinnamon)
      command: >
        gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/
        command 'gnome-system-monitor'
      ignore_errors: yes

    - name: Set System Monitor shortcut (Cinnamon)
      command: >
        gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/
        binding "['<Control><Shift>Escape']"
      ignore_errors: yes

    - name: Register System Monitor shortcut in Cinnamon list
      command: >
        gsettings set org.cinnamon.desktop.keybindings custom-list
        "['/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/']"
      ignore_errors: yes

    # Flameshot (Super+Shift+S)
    - name: Create custom shortcut for Flameshot (Cinnamon)
      command: >
        gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/
        name 'Flameshot'
      ignore_errors: yes

    - name: Set Flameshot command (Cinnamon)
      command: >
        gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/
        command 'flameshot gui'
      ignore_errors: yes

    - name: Set Flameshot shortcut (Cinnamon)
      command: >
        gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/
        binding "['<Super><Shift>S']"
      ignore_errors: yes

    - name: Register Flameshot shortcut in Cinnamon list
      command: >
        gsettings set org.cinnamon.desktop.keybindings custom-list
        "['/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/', '/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/']"
      ignore_errors: yes

    # --- Finish ---
    - name: Notify completion
      debug:
        msg: "✅ Setup complete! Reboot or re-login to apply Docker/Wireshark group changes and keyboard shortcuts."
