---
- name: Install and configure Windows 11 apps
  hosts: windows
  gather_facts: yes

  tasks:

    # 1. Ensure Chocolatey is installed
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    # 2. Install applications
    - name: Install multiple applications via Chocolatey
      win_chocolatey:
        name:
          - steam
          - firefox
          - discord
          - medal
          - wireshark
          - spotify
          - vscode
          - vmwareworkstation
          - vlc
          - minecraft
          - bitwarden
        state: present
        ignore_checksums: yes

    # 3. Configure Taskbar: move to bottom-left
    - name: Configure Taskbar position
      win_shell: |
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" `
        -Name TaskbarAl -Value 0

    # 4. Set background to Featured/Spotlight
    - name: Enable Spotlight background
      win_shell: |
        $RegPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"
        Set-ItemProperty -Path $RegPath -Name "RotatingLockScreenEnabled" -Value 1
        Set-ItemProperty -Path $RegPath -Name "RotatingLockScreenOverlayEnabled" -Value 1
        Set-ItemProperty -Path $RegPath -Name "ContentDeliveryAllowed" -Value 1
      args:
        executable: powershell
