---
- name: windows11_install_apps.yaml
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:

    # 1. Ensure Chocolatey is installed
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    # 2. Install applications
    - name: Install multiple applications
      win_chocolatey:
        name:
          - steam
          - firefox
          - discord
          - medal
          - wireshark
          - spotify
          - vscode
          - vmwareworkstation
          - vlc
          - minecraft
        state: present
        ignore_checksums: yes

    # 3. Configure Taskbar: move to bottom left and remove bloat
    - name: Configure Taskbar (PowerShell)
      win_shell: |
        # Move taskbar icons to left
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name TaskbarAl -Value 0

    # 4. Set background to Windows Spotlight (Featured pictures)
    - name: Set background to Spotlight
      win_shell: |
        $RegPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"
        Set-ItemProperty -Path $RegPath -Name "RotatingLockScreenEnabled" -Value 1
        Set-ItemProperty -Path $RegPath -Name "RotatingLockScreenOverlayEnabled" -Value 1
        Set-ItemProperty -Path $RegPath -Name "ContentDeliveryAllowed" -Value 1
      args:
        executable: powershell
